export const ARTICLE_SET_LOADING = 'ARTICLE_SET_LOADING';
export const ARTICLE_SET_ERROR = 'ARTICLE_SET_ERROR';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLE_BY_ID = 'FETCH_ARTICLE_BY_ID';
export const FETCH_ARTICLES_BY_OWNER = 'FETCH_ARTICLES_BY_OWNER';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
