export const FETCH_USER = 'FETCH_USER';
export const SET_USER = 'SET_USER';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const UPDATE_USER_INFORMATION = 'UPDATE_USER_INFORMATION';
export const DELETE_USER_AVATAR = 'DELETE_USER_AVATAR';
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR';
